# Prometheus Configuration for RustCare Monitoring

global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Alertmanager configuration (uncomment when needed)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#           - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
# rule_files:
#   - "first_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # RustCare Application (when running)
  - job_name: 'rustcare-server'
    static_configs:
      - targets: ['host.docker.internal:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # PostgreSQL Exporter (if added later)
  # - job_name: 'postgres'
  #   static_configs:
  #     - targets: ['postgres-exporter:9187']

  # Redis Exporter (if added later)  
  # - job_name: 'redis'
  #   static_configs:
  #     - targets: ['redis-exporter:9121']

  # Node Exporter (for system metrics, if added later)
  # - job_name: 'node'
  #   static_configs:
  #     - targets: ['node-exporter:9100']

  # MinIO Metrics
  - job_name: 'minio'
    metrics_path: /minio/v2/metrics/cluster
    scheme: http
    static_configs:
      - targets: ['minio:9000']

  # NATS Monitoring
  - job_name: 'nats'
    static_configs:
      - targets: ['nats:8222']
    metrics_path: '/varz'

  # Stalwart Mail Server Metrics
  - job_name: 'stalwart-mail'
    static_configs:
      - targets: ['stalwart-mail:9091']
    metrics_path: '/metrics'
    scrape_interval: 30s